# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTQ2NjBiMjE0ZDVhNTU1ODJiNWFiOTM1MzA1NWJlMTJkYjA1NjQyMGJiODQ2YjMwYzEyZTQ5OTJjOWFiOGI3MmZhYjk3MzU3NTA4MmVmOWQzYmFlMWVmOGIzMWFlM2U3MDc3MWZlMTUwMjViYjJhOGQ5OThhMGI3ZjMyM2RjMTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
